
<div class="main-panel">

	<?php echo \Modules\Navbar::buildNavbar(); ?>

	<div class="content">
		<div class="col-lg-12 col-md-12">
			<div class="container-fluid">
				<div class="row">
                	<div class="col-md-12">
                        <div class="card">
                            <div class="card-content">
								<?php echo \Modules\Forms::Form(); ?>


							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>



</div>




<!--


	<div class="content">
		<div class="col-lg-12 col-md-12">
			<div class="container-fluid">
				<div class="row">


						    <div class="col-md-12">
						        <div class="card">
									<form action="upload.php" method="POST" enctype="multipart/form-data">
										Arquivo: <input type="file" name="file"><br>
										<input type="submit" value="Enviar">
									</form>
								</div>
							</div>
				

				</div>
			</div>
		</div>
	</div>
















<div class="main-panel">

		<?php //echo \Modules\Navbar::buildNavbar(); ?>

		<?php //echo \Modules\ContentDash::Content(); ?>

</div>
-->