<!DOCTYPE html>
<html lang="en">
  


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title><?php $this->getPageTitle('-');?> Salao</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <meta name="viewport" content="width=device-width" />

    <link href="animate.css" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="/../assets/bootstrap/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Custom styles for this template -->
    <link href="/../assets/bootstrap/css/heroic-features.css" rel="stylesheet">


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../../assets/css/demo.css" rel="stylesheet" />

</head>
<body>

     

        <?php $this->content(); ?>

              <!-- Bootstrap core JavaScript -->
    <script src="/assets/bootstrap/jquery/jquery.min.js"></script>
    <script src="/assets/bootstrap/popper/popper.min.js"></script>
    <script src="/assets/bootstrap/bootstrap/js/bootstrap.min.js"></script>
    
  </body>
</html>